/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as AboutFoundersRouteImport } from './routes/about/founders'
import { Route as ServicesIndustrialShedRouteImport } from './routes/services/industrial-shed'
import { Route as ServicesMsStructureRouteImport } from './routes/services/ms-structure'
import { Route as ServicesPebStructureRouteImport } from './routes/services/peb-structure'
import { Route as ServicesRepairRenovationRouteImport } from './routes/services/repair-renovation'
import { Route as ServicesTinRoofingRouteImport } from './routes/services/tin-roofing'
import { Route as ServicesWarehouseShedRouteImport } from './routes/services/warehouse-shed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFoundersRoute = AboutFoundersRouteImport.update({
  id: '/founders',
  path: '/founders',
  getParentRoute: () => AboutRoute,
} as any)
const ServicesIndustrialShedRoute = ServicesIndustrialShedRouteImport.update({
  id: '/industrial-shed',
  path: '/industrial-shed',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMsStructureRoute = ServicesMsStructureRouteImport.update({
  id: '/ms-structure',
  path: '/ms-structure',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPebStructureRoute = ServicesPebStructureRouteImport.update({
  id: '/peb-structure',
  path: '/peb-structure',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRepairRenovationRoute =
  ServicesRepairRenovationRouteImport.update({
    id: '/repair-renovation',
    path: '/repair-renovation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesTinRoofingRoute = ServicesTinRoofingRouteImport.update({
  id: '/tin-roofing',
  path: '/tin-roofing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesWarehouseShedRoute = ServicesWarehouseShedRouteImport.update({
  id: '/warehouse-shed',
  path: '/warehouse-shed',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/videos': typeof VideosRoute
  '/about/founders': typeof AboutFoundersRoute
  '/services/industrial-shed': typeof ServicesIndustrialShedRoute
  '/services/ms-structure': typeof ServicesMsStructureRoute
  '/services/peb-structure': typeof ServicesPebStructureRoute
  '/services/repair-renovation': typeof ServicesRepairRenovationRoute
  '/services/tin-roofing': typeof ServicesTinRoofingRoute
  '/services/warehouse-shed': typeof ServicesWarehouseShedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/videos': typeof VideosRoute
  '/about/founders': typeof AboutFoundersRoute
  '/services/industrial-shed': typeof ServicesIndustrialShedRoute
  '/services/ms-structure': typeof ServicesMsStructureRoute
  '/services/peb-structure': typeof ServicesPebStructureRoute
  '/services/repair-renovation': typeof ServicesRepairRenovationRoute
  '/services/tin-roofing': typeof ServicesTinRoofingRoute
  '/services/warehouse-shed': typeof ServicesWarehouseShedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/videos': typeof VideosRoute
  '/about/founders': typeof AboutFoundersRoute
  '/services/industrial-shed': typeof ServicesIndustrialShedRoute
  '/services/ms-structure': typeof ServicesMsStructureRoute
  '/services/peb-structure': typeof ServicesPebStructureRoute
  '/services/repair-renovation': typeof ServicesRepairRenovationRoute
  '/services/tin-roofing': typeof ServicesTinRoofingRoute
  '/services/warehouse-shed': typeof ServicesWarehouseShedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/videos'
    | '/about/founders'
    | '/services/industrial-shed'
    | '/services/ms-structure'
    | '/services/peb-structure'
    | '/services/repair-renovation'
    | '/services/tin-roofing'
    | '/services/warehouse-shed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/videos'
    | '/about/founders'
    | '/services/industrial-shed'
    | '/services/ms-structure'
    | '/services/peb-structure'
    | '/services/repair-renovation'
    | '/services/tin-roofing'
    | '/services/warehouse-shed'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/projects'
    | '/quote'
    | '/services'
    | '/videos'
    | '/about/founders'
    | '/services/industrial-shed'
    | '/services/ms-structure'
    | '/services/peb-structure'
    | '/services/repair-renovation'
    | '/services/tin-roofing'
    | '/services/warehouse-shed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/founders': {
      id: '/about/founders'
      path: '/founders'
      fullPath: '/about/founders'
      preLoaderRoute: typeof AboutFoundersRouteImport
      parentRoute: typeof AboutRoute
    }
    '/services/industrial-shed': {
      id: '/services/industrial-shed'
      path: '/industrial-shed'
      fullPath: '/services/industrial-shed'
      preLoaderRoute: typeof ServicesIndustrialShedRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ms-structure': {
      id: '/services/ms-structure'
      path: '/ms-structure'
      fullPath: '/services/ms-structure'
      preLoaderRoute: typeof ServicesMsStructureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/peb-structure': {
      id: '/services/peb-structure'
      path: '/peb-structure'
      fullPath: '/services/peb-structure'
      preLoaderRoute: typeof ServicesPebStructureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/repair-renovation': {
      id: '/services/repair-renovation'
      path: '/repair-renovation'
      fullPath: '/services/repair-renovation'
      preLoaderRoute: typeof ServicesRepairRenovationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/tin-roofing': {
      id: '/services/tin-roofing'
      path: '/tin-roofing'
      fullPath: '/services/tin-roofing'
      preLoaderRoute: typeof ServicesTinRoofingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/warehouse-shed': {
      id: '/services/warehouse-shed'
      path: '/warehouse-shed'
      fullPath: '/services/warehouse-shed'
      preLoaderRoute: typeof ServicesWarehouseShedRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface AboutRouteChildren {
  AboutFoundersRoute: typeof AboutFoundersRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutFoundersRoute: AboutFoundersRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface ServicesRouteChildren {
  ServicesIndustrialShedRoute: typeof ServicesIndustrialShedRoute
  ServicesMsStructureRoute: typeof ServicesMsStructureRoute
  ServicesPebStructureRoute: typeof ServicesPebStructureRoute
  ServicesRepairRenovationRoute: typeof ServicesRepairRenovationRoute
  ServicesTinRoofingRoute: typeof ServicesTinRoofingRoute
  ServicesWarehouseShedRoute: typeof ServicesWarehouseShedRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndustrialShedRoute: ServicesIndustrialShedRoute,
  ServicesMsStructureRoute: ServicesMsStructureRoute,
  ServicesPebStructureRoute: ServicesPebStructureRoute,
  ServicesRepairRenovationRoute: ServicesRepairRenovationRoute,
  ServicesTinRoofingRoute: ServicesTinRoofingRoute,
  ServicesWarehouseShedRoute: ServicesWarehouseShedRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
